target 'iosApp' do
  use_frameworks!
  platform :ios, '14.1'
  pod 'UIPilot', '~> 2.0.2'
  pod 'umbrella_ios', :path => '../common/umbrella-ios'
  post_install do |installer|
    installer.pods_project.build_configurations.each do |config|
      config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
    end
  end
end